### ISSUE TITLE
🚀 Add Terraform for deploying Lambda and API Gateway

### ISSUE THREAD

**Issue by npsopheak** [slashdigital/slash-nodejs-api-boilerplate#5]

**Comment by npsopheak** [comment]
Checkout this tutorial: https://learn.hashicorp.com/tutorials/terraform/lambda-api-gateway?in=terraform/aws  and https://www.serverless.com/blog/definitive-guide-terraform-serverless/

@sophatvathana-slash TF with Lambda , requires huge amount of config with tf :D that's why maybe we need the generator....

**Comment by npsopheak** [comment]
```yaml

version 1.0
organization: slash
project: Cool System

apiGateway:
  id: {}

functions:
  todoModule:
    handler: src/function.handler
    route: /{proxy +} or based on controller
    apiGateway: id{}
  userModule:
    handler: src/function.handler
    route: /{proxy +} or based on controller
    apiGateway: id{}
    middleware: {}

```
